### ISSUE TITLE
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.SortedSet.iterator()' on a null object reference         at com.rmondjone.camera.CameraPreview.chooseOptimalSize(CameraPreview.java:158)         at com.rmondjone.camera.CameraPreview.surfaceCreated(CameraPreview.java:79)

### ISSUE THREAD

**Issue by wangchang163** [RmondJone/AndroidCamera#2]

**Comment by Born-alone** [comment]
一样的错误 解决了么

**Comment by wangchang163** [comment]
> 一样的错误 解决了么

放弃它了

**Comment by RmondJone** [comment]
我就是随便写了上传下，没想到这么多人关注🤣🤣🤣有空完善下你们说的问题
